export default [
    {   
        id: 1,
        title: "Al Madinah",
        location: "Saudi-Arabia",
        googleMapsUrl: "https://goo.gl/maps/EdDcyosbGmSUJAUN6",
        startDate: "18 Mar, 2018",
        endDate: "25 Mar, 2018",
        description: "El-Madinah is the most peacefull city, it is a destination for many muslims around the world.",
        imageUrl: "medina.jpg"
    },
    {   id: 2,
        title: "Mecca",
        location: "Saudi-Arabia",
        googleMapsUrl: "https://goo.gl/maps/S5116TfG5XCXgFXu8",
        startDate: "25 Mar, 2018",
        endDate: " 2 Apr, 2018",
        description: "Mecca is a destination for muslims to do pilgrimage (hadj) and it hosts more than 3 million muslim every year, to be considered as the most largest human gathering place in the world.",
        imageUrl: "mecca.jpg"
    },
    {   id:3,
        title: "Wroclaw",
        location: "Poland",
        googleMapsUrl: "https://goo.gl/maps/6ogKgSrrV9MPjEq28",
        startDate: "17 Feb, 2022",
        endDate: "15 Sep, 2022",
        description: "Wroclaw has a weird vibe of mixture between eastern and western EU and its a place for alot of tourist everyyear in poland.",
        imageUrl: "wroclaw.jpg"
    },
    {   id:4,
        title: "Lodz",
        location: "Poland",
        googleMapsUrl: "https://goo.gl/maps/QnjRES9nt1GFt26Y8",
        startDate: "12 Jan, 2021",
        endDate: "24 Jan, 2021",
        description: "Lodz is place in poland that hosts students from around the world to be one of the citties with largest international students.",
        imageUrl: "lodz.jpg"
    },
    {   id:5,
        title: "Silkeborg",
        location: "Denmark",
        googleMapsUrl: "https://goo.gl/maps/xigAyGddSZbdMVWx8",
        startDate: "22 Jun, 2022",
        endDate: "26 Jun, 2022",
        description: "A small and beautifull city in the center of Denmark.",
        imageUrl: "silkeborg.jpg"
    },
    {   id:6,
        title: "Malmo",
        location: "Sweden",
        googleMapsUrl: "https://goo.gl/maps/LDbTidCvpj1a444a8",
        startDate: "19 Nov, 2022",
        endDate: "20 Nov, 2022",
        description: "Malmo is very nice citty due to it variety of connection, one the most important conections is the bridge that connect it to Copenhagen all across the sea.",
        imageUrl: "malmo.jpg"
    }
]